# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 22, 17, 33, 27, 317159, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
